services:
  bpm-gateway:
    build:
      context: .             # Thư mục chứa Dockerfile (ở project root bpm-connector)
      dockerfile: Dockerfile
    container_name: bpm-gateway
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://10.6.18.22:5432/coresys
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 123456
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
      AUTH_JWT_SECRET: mySuperSecretKey1234567890123456
      SERVER_PORT: 8080
    restart: unless-stopped
