version: "3.9"

services:
  bpm-gateway:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bpm-gateway
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/coresys
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 123456
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
      AUTH_JWT_SECRET: mySuperSecretKey1234567890123456
	  APP_AUTH_DEFAULT_USERNAME: admin
	  APP_AUTH_DEFAULT_PASSWORD: 123456
      SERVER_PORT: 8080
    restart: unless-stopped
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: coresys
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
