spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bpm_db
    username: bpm_user
    password: bpm_pass

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration

server:
  port: 8080
