spring:
  application:
    name: bpm-connector
  datasource:
<<<<<<< HEAD
#    url: jdbc:postgresql://10.6.18.24:5432/coresys
    url: jdbc:postgresql://0.0.0.0:5432/coresys
=======
    url: jdbc:postgresql://10.6.18.23:30432/coresys
>>>>>>> 0fdb0a67777ff4a4a20f86f9656a1eff1403f196
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver
    hikari:
        minimum-idle: 0               # Không giữ connection thừa
        maximum-pool-size: 5          # Pool nhỏ, vừa đủ
        idle-timeout: 10000           # 10s timeout
        max-lifetime: 30000           # 30s max sống
        connection-timeout: 3000      # 3s timeout kết nối
        validation-timeout: 2000      # 2s timeout khi test connection
        connection-test-query: SELECT 1
        initialization-fail-timeout: 0
  
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true  # Cho phép chạy trên DB đã có dữ liệu
    clean-disabled: true       # Không cho phép xóa DB bằng Flyway (bảo vệ)
    out-of-order: false 
    placeholders.enabled: false

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  thymeleaf:
    cache: false

# security:
#   user:
#     name: admin
#     password: secret

auth:
  jwt:
    secret: mySuperSecretKey1234567890123456

app:
  cmis:
    atompubUrl: "http://172.29.255.121:9081/fncmis/resources/Service"
    repositoryId: "OBJ"
    username: "ecmadmin"
    password: "Car3full"
    connectTimeoutMs: 10000
    readTimeoutMs: 30000
    defaultObjectTypeId: "cmis:document"
    defaultFolderPath: "/UPLOAD_TEMP"

springdoc:
  api-docs:
    path: /api-docs   # endpoint JSON OpenAPI
  swagger-ui:
    path: /swagger-ui.html   # UI page
    operationsSorter: method
    tagsSorter: alpha

server:
  port: 8080