spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://10.6.18.22:5432/coresys}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:123456}
    driver-class-name: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME:org.postgresql.Driver}
    hikari:
      minimum-idle: 0
      maximum-pool-size: 5
      idle-timeout: 10000
      max-lifetime: 30000
      connection-timeout: 3000
      validation-timeout: 2000
      connection-test-query: SELECT 1
      initialization-fail-timeout: 0

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    clean-disabled: true
    out-of-order: false
    placeholders.enabled: false

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  thymeleaf:
    cache: false		

auth:
  jwt:
    secret: ${AUTH_JWT_SECRET:mySuperSecretKey1234567890123456}

server:
  port: ${SERVER_PORT:8080}
  
app:
  cmis:
    atompubUrl: "http://172.29.255.121:9081/fncmis/resources/Service"
    repositoryId: "OBJ"
    username: "ecmadmin"
    password: "Car3full"
    connectTimeoutMs: 10000
    readTimeoutMs: 30000
    defaultObjectTypeId: "cmis:document"
    defaultFolderPath: "/UPLOAD_TEMP"

springdoc:
  api-docs:
    path: /api-docs   # endpoint JSON OpenAPI
  swagger-ui:
    path: /swagger-ui.html   # UI page
    operationsSorter: method
    tagsSorter: alpha
