spring:
  datasource:
	url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://10.6.18.23:30432/coresys}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:123456}
    driver-class-name: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME:org.postgresql.Driver}

app:
  auth:
    default:
      username: ${APP_AUTH_DEFAULT_USERNAME:admin}
      password: ${APP_AUTH_DEFAULT_PASSWORD:123456}

auth:
  jwt:
    secret: ${AUTH_JWT_SECRET:mySuperSecretKey1234567890123456}

server:
  port: ${SERVER_PORT:8080}
