spring:
  application:
    name: bpm-connector
  datasource:
#    url: jdbc:postgresql://10.6.18.24:5432/coresys
    url: jdbc:postgresql://0.0.0.0:5432/coresys
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver
    hikari:
        minimum-idle: 0               # Không giữ connection thừa
        maximum-pool-size: 5          # Pool nhỏ, vừa đủ
        idle-timeout: 10000           # 10s timeout
        max-lifetime: 30000           # 30s max sống
        connection-timeout: 3000      # 3s timeout kết nối
        validation-timeout: 2000      # 2s timeout khi test connection
        connection-test-query: SELECT 1
        initialization-fail-timeout: 0
  
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true  # Cho phép chạy trên DB đã có dữ liệu
    clean-disabled: true       # Không cho phép xóa DB bằng Flyway (bảo vệ)
    out-of-order: false 
    placeholders.enabled: false

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true

  thymeleaf:
    cache: false

# security:
#   user:
#     name: admin
#     password: secret

logging:
  level:
    org.hibernate.SQL: OFF
    org.hibernate.type.descriptor.sql.BasicBinder: OFF

auth:
  jwt:
    secret: mySuperSecretKey1234567890123456

springdoc:
  api-docs:
    path: /api-docs   # endpoint JSON OpenAPI
  swagger-ui:
    path: /swagger-ui.html   # UI page
    operationsSorter: method
    tagsSorter: alpha

server:
  port: 8080