spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bpm_db
    username: bpm_user
    password: bpm_password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

logging:
  level:
    root: INFO
    com.bpm: DEBUG
